# Site settings
title: Philipp Hirsch
email: info@hanspolo.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hanspolo.net" # the base hostname & protocol for your site
twitter_username: hanspolo_
github_username:  hanspolo
xing_username:
bitcoin_address: 1K7yqRtZ3vniEQAPvH94UG991jnsuqqHfk

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
